---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: src/_data/sections/portfolio.json
  label: Porfolios
  match: "**/*"
- type: document
  path: src/_data/sections/banner.json
  label: Banners
upload_dir: rooster
public_path: ''
front_matter_path: "/upload"
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
