backend:
  name: git-gateway
  branch: master # Branch to update
media_folder: "src/assets/img"
public_folder: "/assets/img"
publish_mode: editorial_workflow

collections:
  - name: "home"
    label: "Home"
    preview_path: ""
    files:
      - label: "Banner"
        name: "banner"
        file: "src/_data/sections/banner.json"
        fields:
          - label: "Banners"
            name: "banners"
            widget: "list"
            fields:
              - name: "image"
                label: "Slide"
                widget: "image"
              - name: "icon"
                label: "Icon"
                widget: "image"
              - name: "subtitle"
                label: "Sub Title"
                widget: "string"
              - name: "title"
                label: "Title"
                widget: "string"
              - name: "video"
                label: "Video Url"
                widget: "string"
                required: false
      - label: "Services"
        name: "service"
        file: "src/_data/sections/service.json"
        fields:
          - name: "services"
            label: "Service"
            widget: "list"
            fields:
              - name: "name"
                label: "Name"
                widget: "string"
              - name: "description"
                label: "Description"
                widget: "string"
              - name: "icon"
                label: "Icon"
                widget: "image"
      - label: "Portfolios"
        name: "portfolio"
        file: "src/_data/sections/portfolio.json"
        fields:
          - name: "portfolios"
            widget: "list"
            label: "Portfolios"
            fields:
              - name: "name"
                label: "Name"
                widget: "string"
              - name: "thumnail"
                label: "Thumnail"
                widget: "image"
              - label: "Gallery"
                required: false
                name: "galleryImages"
                widget: "list"
                field:
                  {
                    label: "Image",
                    name: "image",
                    widget: "image",
                    required: false,
                  }
              - label: "Video"
                name: "videoUrl"
                widget: "string"
                required: false
              - name: "link"
                required: false
                label: "Link"
                widget: "object"
                fields:
                  - {
                      name: "text",
                      label: "Text",
                      widget: "string",
                      required: false,
                    }
                  - {
                      name: "url",
                      label: "Url",
                      widget: "string",
                      required: false,
                    }
      - label: "Meta"
        name: "meta"
        file: "src/index.md"
        fields:
          - { name: "title", label: "Text", widget: "string" }
          - { name: "description", label: "Description", widget: "string" }
          - { name: "siteUrl", label: "Site Url", widget: "string" }
          - { name: "siteName", label: "Site Name", widget: "string" }
          - { name: "imgSrc", label: "Image", widget: "image" }
          - { name: "imgAtl", label: "Image Alt", widget: "string" }
  - name: "components"
    label: "Components"
    files:
      - name: "header"
        label: "Header"
        file: "src/_data/header.json"
        fields:
          - name: "brandTitle"
            label: "Brand Title"
            widget: "string"
          - name: "nav"
            label: "Navigation Bar"
            widget: "list"
            fields:
              - { name: "label", label: "Label", widget: "string" }
              - { name: "url", label: "Url", widget: "string" }
      - name: "footer"
        label: "Footer"
        file: "src/_data/footer.json"
        fields:
          - name: "title"
            label: "Title"
            widget: "string"
          - name: "contact"
            label: "Contact"
            widget: "list"
            fields:
              - { name: "text", label: "Text", widget: "string" }
              - { name: "icon", label: "Icon", widget: "image" }
          - name: "copyRight"
            label: "Copy Right"
            widget: "string"
          - name: "madeBy"
            label: "Made By"
            widget: "object"
            fields:
              - { name: "author", label: "Author", widget: "string" }
              - { name: "url", label: "Url", widget: "string" }
  - name: "settings"
    label: "App Settings"
    files:
      - name: "settings"
        label: "Settings"
        file: "src/_data/settings.json"
        fields:
          - name: "socials"
            label: "Social Item"
            widget: "list"
            fields:
              - { name: "name", label: "Name", widget: "string" }
              - { name: "icon", label: "Icon", widget: "image" }
              - { name: "url", label: "Url", widget: "string" }
