backend:
  name: git-gateway
  branch: master # Branch to update
media_folder: 'assets/img'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home Page'
        name: 'homePage'
        file: 'src/index.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Banners'
            name: 'banners'
            widget: 'list'
            field: { label: 'Slide', name: 'slide', widget: 'image' }
          - label: 'Services'
            name: 'services'
            widget: 'list'
            fields:
              - name: 'name'
                label: 'Name'
                widget: 'string'
              - name: 'image'
                label: 'Image'
                widget: 'image'
          - label: 'Portfolios'
            name: 'portfolios'
            widget: 'list'
            fields:
              - name: 'name'
                label: 'Name'
                widget: 'string'
              - name: 'image'
                label: 'Image'
                widget: 'image'
              - name: 'description'
                label: 'Description'
                widget: 'string'
              - name: 'link'
                label: 'Link'
                widget: 'object'
                fields:
                  - { name: 'text', label: 'Text', widget: 'string' }
                  - { name: 'url', label: 'Url', widget: 'string' }
