backend:
  name: git-gateway
  branch: master # Branch to update
media_folder: '_site/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home Page'
        name: 'homePage'
        file: 'index.md'
        fields: [{ - label: 'Title', name: 'title', widget: 'string' }]
